-- Criação do banco de dados
CREATE DATABASE IntegratedGovernanceDB;

-- Uso do banco de dados criado
USE IntegratedGovernanceDB;

-- Criação da tabela DataGovernanceRoles
CREATE TABLE DataGovernanceRoles (
    ID_DATAGOVERNANCEROLES INT AUTO_INCREMENT PRIMARY KEY,
    ROLENAME VARCHAR(255) NOT NULL
);

-- Criação da tabela PersonalData
CREATE TABLE PersonalData (
    ID_PERSONALDATA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    CPF VARCHAR(11),
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(255)
);

-- Criação da tabela DataGovernanceEntities
CREATE TABLE DataGovernanceEntities (
    ID_DATAGOVERNANCEENTITIES INT AUTO_INCREMENT PRIMARY KEY,
    ID_DATAGOVERNANCEROLES INT,
    ID_PERSONALDATA INT,
    RAZAO_SOCIAL VARCHAR(255),
    CNPJ VARCHAR(14),
    FINALIDADE_CONTRATACAO VARCHAR(255),
    LOGO BLOB,
    FOREIGN KEY (ID_DATAGOVERNANCEROLES) REFERENCES DataGovernanceRoles(ID_DATAGOVERNANCEROLES),
    FOREIGN KEY (ID_PERSONALDATA) REFERENCES PersonalData(ID_PERSONALDATA)
);
